"""Phase 8 final-validation tests."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from orca_gui.config.orca_keywords import BASIS_SET_OPTIONS, GRID_OPTIONS, METHOD_OPTIONS, SOLVATION_METHOD_OPTIONS


def _load_expected_features(repo_root: Path) -> list[str]:
    content = (repo_root / "tests" / "expected_features.md").read_text(encoding="utf-8")
    return [line[2:].strip() for line in content.splitlines() if line.startswith("- ")]


def test_expected_features_inventory_matches_phase8_audit(repo_root: Path) -> None:
    expected = _load_expected_features(repo_root)
    manual_content = (repo_root / "docs" / "MANUAL_EXCERPTS.md").read_text(encoding="utf-8")
    static_layout = (repo_root / "orca_gui" / "ui" / "layouts" / "static_layout.py").read_text(encoding="utf-8")
    validator = (repo_root / "orca_gui" / "core" / "validator.py").read_text(encoding="utf-8")
    script_generator = (repo_root / "orca_gui" / "generators" / "script_generator.py").read_text(encoding="utf-8")
    excited_golden = (repo_root / "tests" / "golden" / "excited_nacme.inp").read_text(encoding="utf-8").lower()

    feature_checks = {
        "Ground-state static energy generation": (repo_root / "tests" / "golden" / "static_energy.inp").exists(),
        "Ground-state optimization generation": (repo_root / "tests" / "golden" / "optimization.inp").exists(),
        "Ground-state frequency generation": (repo_root / "tests" / "golden" / "frequency.inp").exists(),
        "Excited-state TDDFT/CIS-style generation": "%tddft" in excited_golden,
        "NACME True option visible whenever excited state is selected": 'st.checkbox("NACME True"' in static_layout,
        "Ground-state molecular dynamics generation with `MD` and `%md`": "! MD " in (repo_root / "tests" / "golden" / "ground_md_template.inp").read_text(encoding="utf-8"),
        "Standalone Python batch-script generation with absolute XYZ pathing": "os.path.abspath" in script_generator,
        "Batch no-overwrite safeguards for existing `.inp` files": "--overwrite_inps" in script_generator,
        "Simple input and block-design generation paths": "input_design" in (repo_root / "orca_gui" / "core" / "input_generator.py").read_text(encoding="utf-8"),
        "Uploaded XYZ file priority over pasted XYZ text": "Prioritizing the uploaded XYZ file." in validator,
        "`%pal nprocs` and `%maxcore` generation": "%pal nprocs 4 end" in (repo_root / "tests" / "golden" / "static_energy.inp").read_text(encoding="utf-8"),
        "Curated `CPCM`, `CPCMC`, `SMD`, and limited `COSMORS` support": {item.keyword for item in SOLVATION_METHOD_OPTIONS} == {"CPCM", "CPCMC", "SMD", "COSMORS"},
        "Curated `DEFGRID1`, `DEFGRID2`, and `DEFGRID3` support": {item.keyword for item in GRID_OPTIONS} == {"DEFGRID1", "DEFGRID2", "DEFGRID3"},
        "Top-5 curated DFT functional and basis-set dropdown catalogs": len(METHOD_OPTIONS) >= 5 and len(BASIS_SET_OPTIONS) >= 5,
        "Manual excerpt generation from the attached ORCA 6.1 PDF": "Auto-generated by `scripts/generate_manual_excerpts.py`." in manual_content,
    }

    assert set(expected) == set(feature_checks)
    assert all(feature_checks.values())


def test_cluster_smoke_results_summary_is_green(repo_root: Path) -> None:
    results_root = repo_root / "tests" / "cluster_smoke_bundle" / "results"
    summary = json.loads((results_root / "summary.json").read_text(encoding="utf-8"))

    assert len(summary) == 6
    assert all(case["returncode"] == 0 for case in summary)

    for case in summary:
        out_path = results_root / case["case"] / f'{case["case"]}.out'
        out_text = out_path.read_text(encoding="utf-8", errors="replace")
        assert "****ORCA TERMINATED NORMALLY****" in out_text
        assert "Program Version" in out_text


def test_phase8_validation_script_writes_report(repo_root: Path, tmp_path: Path) -> None:
    script_path = repo_root / "scripts" / "run_phase8_validation.py"
    output_path = tmp_path / "PHASE8_VALIDATION.md"

    subprocess.run(
        [sys.executable, str(script_path), "--repo-root", str(repo_root), "--output", str(output_path)],
        check=True,
        cwd=repo_root,
    )

    report = output_path.read_text(encoding="utf-8")
    assert "# Phase 8 Validation Report" in report
    assert "## Cluster Smoke Results" in report
    assert "Observed ORCA version(s) in returned cluster outputs: `6.0.1`" in report
    assert "Ground-state molecular dynamics generation with `MD` and `%md`" in report
