"""Python batch script generator for multi-frame ORCA input creation."""

from __future__ import annotations

import json
import re
from textwrap import dedent

from orca_gui.core.input_generator import ORCAInputGenerator
from orca_gui.models.session_state import SessionState


class BatchScriptGenerator:
    """Generate a standalone Python batch script with argparse and tqdm."""

    def __init__(self, state: SessionState, input_generator: ORCAInputGenerator | None = None) -> None:
        self.state = state
        self.input_generator = input_generator or ORCAInputGenerator()

    @staticmethod
    def output_filename(state: SessionState) -> str:
        """Return a predictable batch-script download filename."""

        prefix = state.batch_filename_prefix.strip("_- ") or "orca"
        safe_prefix = re.sub(r"[^A-Za-z0-9_-]+", "_", prefix).strip("_") or "orca"
        return f"generate_{safe_prefix}_batch.py"

    def _input_template(self) -> str:
        """Render the embedded ORCA input template with an XYZ placeholder."""

        generated = self.input_generator.render_xyzfile_template(self.state, "{XYZ_PATH}")
        if not generated.validation.passed:
            joined_errors = "; ".join(generated.validation.errors)
            raise ValueError(f"Cannot build batch script from invalid state: {joined_errors}")
        return generated.text

    def generate(self) -> str:
        """Return the standalone batch generation script."""

        input_template_literal = json.dumps(self._input_template())
        example_base_dir = json.dumps(self.state.batch_base_dir or r"C:\path\to\frames")

        script = f"""
#!/usr/bin/env python3
### Caldera: Orca Input file Generator ###
# Developer: Ajay Khanna | LANL | May 2026
# Generated by the Phase 6 batch workflow.
\"\"\"Generated Batch ORCA Input Creator.\"\"\"

import argparse
import os
from pathlib import Path

from tqdm import tqdm


INPUT_TEMPLATE = {input_template_literal}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Batch generate ORCA inputs.")
    parser.add_argument("--base_dir", required=True, help="Base directory containing XYZ frame subdirectories.")
    parser.add_argument("--xyz_prefix", default={json.dumps(self.state.batch_xyz_prefix)}, help="Prefix for XYZ files.")
    parser.add_argument("--start_frame", type=int, default={self.state.batch_start_frame}, help="First frame number.")
    parser.add_argument("--end_frame", type=int, default={self.state.batch_end_frame}, help="Last frame number.")
    parser.add_argument("--step_frame", type=int, default={self.state.batch_step_frame}, help="Frame increment.")
    parser.add_argument("--output_prefix", default={json.dumps(self.state.batch_filename_prefix)}, help="Prefix for generated input files.")
    parser.add_argument("--subdir_pattern", default={json.dumps(self.state.batch_subdir_pattern)}, help="Pattern for per-frame subdirectories. Use an empty string to keep files directly in base_dir.")
    parser.add_argument("--overwrite_inps", action="store_true", help="Overwrite existing .inp files instead of skipping them.")
    return parser


def generate_input_content(abs_xyz_path: str) -> str:
    return INPUT_TEMPLATE.replace("{{XYZ_PATH}}", abs_xyz_path)


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.start_frame < 1:
        parser.error("--start_frame must be at least 1.")
    if args.end_frame < args.start_frame:
        parser.error("--end_frame must be greater than or equal to --start_frame.")
    if args.step_frame < 1:
        parser.error("--step_frame must be at least 1.")

    base_dir = Path(args.base_dir).expanduser().resolve()
    generated = 0
    skipped = 0
    failures = 0

    for frame in tqdm(range(args.start_frame, args.end_frame + 1, args.step_frame), desc="Frames"):
        subdir = base_dir / args.subdir_pattern.format(frame) if args.subdir_pattern else base_dir
        xyz_file = subdir / f"{{args.xyz_prefix}}{{frame}}.xyz"
        inp_file = subdir / f"{{args.output_prefix}}{{frame}}.inp"

        if not xyz_file.exists():
            print(f"Warning: {{xyz_file}} not found, skipping...")
            failures += 1
            continue

        if inp_file.exists() and not args.overwrite_inps:
            print(f"Warning: {{inp_file}} already exists, skipping...")
            skipped += 1
            continue

        try:
            abs_xyz_path = os.path.abspath(xyz_file)
            inp_content = generate_input_content(abs_xyz_path)
            inp_file.write_text(inp_content, encoding="utf-8")
            generated += 1
        except Exception as exc:
            print(f"Failed on frame {{frame}}: {{exc}}")
            failures += 1

    print(f"\\nSummary: {{generated}} Generated, {{skipped}} Skipped, {{failures}} Failures.")


if __name__ == "__main__":
    main()
"""
        example_comment = dedent(
            f"""\
            # Example usage:
            #   python {self.output_filename(self.state)} --base_dir {example_base_dir}
            """
        )
        return example_comment + dedent(script).strip() + "\n"
